name: mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kiwi: ^0.1.0
  flutter_bloc: 0.6.0
  meta: ^1.1.6
  equatable: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0
  build_runner: ^0.10.1
  kiwi_generator: ^0.1.1

  firebase_auth: ^0.6.6
  google_sign_in: ^3.2.4

flutter:
  uses-material-design: true

assets: