name: mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  kiwi: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.10.1
  kiwi_generator: ^0.1.1
  flutter_bloc: 0.4.11
  firebase_core: ^0.3.0
  firebase_database: ^2.0.1

flutter:
  uses-material-design: true
